package com.example.cashguard.ViewModel

import android.app.Application
import android.util.Log
import androidx.core.content.ContextCompat
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.viewModelScope
import com.example.cashguard.Database.AppDatabase
import com.example.cashguard.Helper.SessionManager
import com.example.cashguard.R
import com.example.cashguard.Repository.BudgetRepository
import com.example.cashguard.Repository.CategoryRepository
import com.example.cashguard.Repository.UserRepository
import com.example.cashguard.data.Category
import kotlinx.coroutines.launch
import java.util.Calendar

class RegisterViewModel(application: Application) : AndroidViewModel(application) {

    private val userRepository: UserRepository
    private val categoryRepository: CategoryRepository
    private val budgetRepository: BudgetRepository

    private val sessionManager: SessionManager

    private val _toastMessage = MutableLiveData<String?>()
    val toastMessage: LiveData<String?> = _toastMessage

    private val _registerState = MutableLiveData<Boolean?>()
    val registerState: LiveData<Boolean?> = _registerState

    init {
        val userDao = AppDatabase.getInstance(application).userDao()
        userRepository = UserRepository(userDao)

        val categoryDao = AppDatabase.getInstance(application).categoryDao()
        categoryRepository = CategoryRepository(categoryDao)

        val budgetDao = AppDatabase.getInstance(application).budgetDao()
        budgetRepository = BudgetRepository(budgetDao)

        sessionManager = SessionManager(application)
    }

    companion object {
        val DEFAULT_CATEGORIES = listOf(
            Triple("Food & Drink", "Expense", R.color.red),
            Triple("Transport", "Expense", R.color.blue_light),
            Triple("Household", "Expense", R.color.yellow),
            Triple("Entertainment", "Expense", R.color.violet),
            Triple("Subscription", "Expense", R.color.green),
            Triple("Salary", "Income", R.color.stroke)
        )
    }

    fun onRegisterClicked(firstName: String, lastName: String, email: String, password: String, confirmPassword: String) {

        if (firstName.isBlank() || lastName.isBlank() || email.isBlank() || password.isBlank()) {
            _toastMessage.value = "Please enter in all details."
            return
        }
        if (password.length < 4) {
            _toastMessage.value = "Password must be at least 4 characters long."
            return
        }
        if (password != confirmPassword) {
            _toastMessage.value = "Passwords do not match."
            return
        }

        viewModelScope.launch {
            if (userRepository.getUserByEmail(email) != null) {
                _toastMessage.value = "Registration failed, this email already exists."
                return@launch
            }
            try {
                val userId = userRepository.insertUserAndGetId(firstName, lastName, email, password)
                _toastMessage.value = "Registration successful!"

                initializeUser(userId)
            } catch (e: Exception) {
                _toastMessage.value = "Registration failed, please try again later."
                return@launch
            }
        }
    }

    private fun initializeUser(userId: String) {
        viewModelScope.launch {
            try {
                // ENSURE THIS IS THE ABSOLUTE START OF THE MONTH
                val startOfMonth = Calendar.getInstance().apply { set(Calendar.DAY_OF_MONTH, 1) }.time
                val endOfMonth = Calendar.getInstance().apply { add(Calendar.MONTH, 1); set(Calendar.DAY_OF_MONTH, 1); add(Calendar.DATE, -1) }.time
                val budgetId = budgetRepository.createBudget(userId, startOfMonth, endOfMonth)
                createDefaultCategories(userId, budgetId)

            } catch (e: Exception) {
                // If any step fails, log the error and update the UI state to show failure.
                Log.e("RegisterViewModel", "Registration process failed", e)
                _registerState.value = false // Or use a more descriptive error state
            }
        }
    }

    // Make sure this private helper function is also in your RegisterViewModel.
    private fun createDefaultCategories(userId: String, budgetId: String) {
        val context = getApplication<Application>().applicationContext

        // Map the default data to Category objects.
        val defaultCategories = DEFAULT_CATEGORIES.map { (name, type, colorResId) ->
            Category(
                categoryId = "", // The ID will be generated by the repository.
                userId = userId,
                budgetId = budgetId, // Assign the new default budget's ID.
                name = name,
                type = type,
                minGoal = null,
                maxGoal = null,
                color = ContextCompat.getColor(context, colorResId),
                isActive = true
            )
        }

        Log.d("RegisterViewModel", "Preparing to insert ${defaultCategories.size} default categories.")
        viewModelScope.launch {
            // The repository will handle creating unique IDs and inserting into Firebase/Room.
            categoryRepository.insertCategories(defaultCategories)
            Log.d("RegisterViewModel", "Successfully inserted default categories. Registration complete.")
            // Final success state is set here, at the end of the entire chain.
            _registerState.value = true
        }
    }

//    private fun createDefaultCategories(userId: String) {
//        val context = getApplication<Application>().applicationContext
//        val defaultCategories = DEFAULT_CATEGORIES.map { (name, type, colorResId) ->
//            Category(
//                userId = userId,
//                name = name,
//                type = type,
//                budgetAmount = null,
//                color = ContextCompat.getColor(context, colorResId)
//            )
//        }
//        Log.d("RegisterViewModel", "Creating ${defaultCategories.size} default categories.")
//        viewModelScope.launch {
//            categoryRepository.insertCategories(defaultCategories)
//            Log.d("RegisterViewModel", "Inserted default categories.")
//            _registerState.value = true
//        }
//    }

    fun onToastMessageShown() {
        _toastMessage.value = null
    }

}

